image: docker:latest

services:
  - docker:dind

build_and_push:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t twitter-bridge .
    - docker tag twitter-bridge "$CI_REGISTRY"/programaker-project/bridges/twitter-bridge:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY"/programaker-project/bridges/twitter-bridge:$CI_COMMIT_SHA
  only:
    - develop
    - master
